endlessm/eos-desktop-extension

- ui/appDisplay.js
As per design decision, make the app grid horizontal. This
is implemented through the 'teardown & rebuild' approach
where all related actors are initially removed from their
parents, and then readded to the new location.
In the case of PagesIndicator, it is necessary to create
a new instance, because BaseAppView uses different classes
depending on the orientation.
The scrollbar adjustment handling required some handholding
and (reasonably) assumes that the vertical adjustment won't
change when the scroll view's vscroll policy is NONE.
https://phabricator.endlessm.com/T30544
> Make the app grid horizontal

- ui/appDisplay.js
- ui/layout.js
- ui/overview.js
A couple of small preparation commits, and finally the one adding the desktop grid clone.
There are various tweaks that still need to be done, specially in the window picker page, but this gets us even closer to the Endless OS desktop.
https://phabricator.endlessm.com/T30543
> App Grid Clone

- stylesheet.scss
- ui/appDisplay.js
- ui/layout.js
- ui/overview.js
- ui/viewSelector.js
- ui/workspaceMonitor.js
- utils.js
A good dozen changes fine-tuning the behavior of the overview in various edge cases; limiting the icon sizes of the app grid to 64px; and adjusting the position of the panel ghost depending on whether or not the eos-panel extension is enabled.
> Polishing, round 1

- ui/layout.js
Some of the DnD changes don't actually depend on the
actor being pickable, and can pretty easily break the
clones.
Disable DnD on these clones.
> layout: Disable DnD on app grid clones

- ui/viewSelector.js
Otherwise, we make both the fade-to-app-grid animation and
the back-to-original-position animations run in parallel.
https://phabricator.endlessm.com/T30738
> viewSelector: Toggle checkbutton after overview is hidden

- settings.js
So it still preserves the position of the app center icon that Endless OS <= 3.8 had.
https://phabricator.endlessm.com/T30787
> migration: Append app center icon to migrated icons

- ui/viewSelector.js
Clicking in the secondary-icon-button on the search bar is triggering
the long-press event for the bgMenuClickAction.
This patch release the background menu click action when this button is
clicked, so the menu is not shown.
This is a workaround to fix this issue, but maybe the best way to solve
this problem is to detect why the long-press event is emitted when the
click is a one click.
https://phabricator.endlessm.com/T30860
> viewSelector: disable bgMenu click on search bar

- extension.js
- ui/layout.js
This makes sure the overview is updated after the overrides are in place and avoids updating it while setting up the overrides.
https://phabricator.endlessm.com/T30597
> extension: Enable workspace monitor after configuring overrides

- ui/layout.js
We absolutely never want clones to actually save pages. With
the latest fixes from GNOME Shell, it is possible that the
clones end up saving pages, due to FolderIcon sending the
'apps-changed' signal.
Override the '_savePages' function from clones with an empty
stub.
https://phabricator.endlessm.com/T30808
> layout: Don't allow clones to save pages

- ui/layout.js
This is, once again, another case of FBO contents not
being invalidated properly. In this case, what happens
is that the icon grid doesn't relayout when unmapped,
which skips marking it as dirty, which doesn't trigger
an FBO invalidation and redraw on both the offscreen
cache, and (most importantly) the desaturation effect.
This can be verified by disabling the desaturation
effect and noticing that invalidation happens on one
of the offscreen caches, and thus triggering a redraw
of the grid.
This is ultimately a problem in the paint machinery of
Clutter, but we can easily work around it by forcing the
actor to be marked as dirty after all parents are mapped.
https://phabricator.endlessm.com/T30964
> layout: Make grid dirty when clone is mapped

- ui/layout.js
The 'upper' property of the clones' adjustments are only
updated after the first time it's mapped. However, at this
point, the real app grid itself may be on another page. The
clones can't reflect that because their adjustments' 'upper'
property is not yet updated with the number of pages.
Bind the 'upper' property of the real app grid's adjustments
with the clones'. This is fine because the number of pages
is decided based on the number of icons, not in the available
space.
https://phabricator.endlessm.com/T30964
> layout: Also bind 'upper' on adjustments

- stylesheet.scss
- ui/appDisplay.js
This makes it easier to drag icons between pages.
> style: Add margins around horizontal app display

- ui/appDisplay.js
Hijack the layout manager to think the adapted size
changed, which makes it skip the easing of the icon
allocation.
https://phabricator.endlessm.com/T31015
> appDisplay: Don't ease allocation of clones

- settings.js
As reported by Damián, and as suggested by the documentation
of the utils function, the folder name can be NULL.
Protect against that.
> settings: Fix NULL folder name

- ui/appDisplay.js
- ui/appSystem.js
This change makes sure that if an app got renamed, is uninstalled but is still referred to in the grid config, the app replacing it will
be placed in the same position in the grid as the old one.
https://phabricator.endlessm.com/T31263
> Respect renamed apps' grid position when applicable

- settings.js
We are removing all web links from the OS, let's remove the special handling here also.
Depends on whether we are also dropping image personalities' specific web links - see endlessm/eos-image-builder#975.
https://phabricator.endlessm.com/T31560
> settings: Remove eos-link-* special handling

- ui/internetSearch.js
I noticed today that the message:
Search %s for "%s"
this string is translated into French as:
Rechercher "%s" sur %s
or, back into English, as:
Search "%s" on %s
That is, the sentence is rewritten to swap the placeholders. In
principal this is fine because the translator can use the POSIX
parameter field extension to explicitly select which parameter to use:
Rechercher "%2$s" sur %1$s
However Transifex does not seem to support that. As a result the French
translation comes out as:
Rechercher "Google" sur my search terms
rather than the intended:
Rechercher "my search terms" sur Google
If I manually use the %2$s notation in the Transifex web editor, it gets
upset with me because this string does not appear in the source text.
So, let's try making it explicit. …
> internetSearch: Use numbered placeholders

- ui/layout.js
- ui/search.js
Previously we customised the search entry to say ‘Search Google and
more…’, but this led users to believe the search entry was just for
searching the internet. In reality, it’s for searching everything,
including all the local content which is such a focus of Endless OS.
Stop customising the text and leave it at the default ‘Type to search’
as set by GNOME.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
https://phabricator.endlessm.com/T31448
> ui: Drop custom search entry text

- meson.build
- metadata.json.in
Deriving the supported version from the package version never
actually worked, but we got away with it because Shell disabled
extension version checks. Now that it's re-enabled, Shell is
actively preventing the desktop extension to load.
Manually set the version field in the extension metadata.
> metadata: Manually set version field

- settings.js
This was introduced so that we could cause Hack to appear on the desktop
for existing users. (Changing the default grid layout would not have
done anything in that case.)
However, this special-case has several downsides:
- It is hard to put Hack somewhere else on the grid in a custom image.
(As an implementation detail, it can be placed in a folder.)
- If Hack is not installed, or has been placed in a folder, a space is
still reserved for it on the first page, so there is always a blank
space there.
Remove this special case in favour of explicitly placing Hack in the
default icon grid layout. https://github.com/endlessm/eos-shell-content/pull/254
On existing systems which update to a version of Endless containing this
change, newly-created user accounts will likely *not* get Hack in the …
> settings: Remove Hack Clubhouse special case

- extension.js
- ui/appDisplay.js
- ui/search.js
This includes search results. In this case, we want to
hide the overview even when no apps are open.
This change includes activating search results too - some
of which are app icons, others are list rows.
https://phabricator.endlessm.com/T33020
> Force hide overview when activating app icons

- ui/dash.js
We need to account that the monitor layout state when the extension
is enable may change, otherwise the cursor barrier can get stuck in
weird places.
Do that by accounting for Main.layoutManager's 'monitors-changed'
signal, and global.display's 'workareas-changed' signals. The
combination of these two signals is apparently enough to cover all
cases where the cursor barrier needs to be recalculated.
https://phabricator.endlessm.com/T33055
> dash: Update barrier when monitor layout changes

- ui/overview.js
- ui/workspaceMonitor.js
GNOME Shell enables extensions very early in the startup process,
after creating most of the main actor tree, but before actually
running the startup animation.
When the eos-desktop-extension is enabled, WorkspaceMonitor calls
_updateOverview(). During startup, naturally, there are no running
apps, so _updateOverview() ends up calling Main.overview.showApps().
Overview.showApps() then performs the regular overview routines,
and emits the Overview::showing signal. SearchController, which
is connected to this signal, reacts by connecting to the 'key-press'
event of global.stage:
```
Main.overview.connect('showing', () => {
this._stageKeyPressId =
global.stage.connect('key-press-event', this._onStageKeyPress.bind(this));
});
```
The problem is in the code above: notice that this callback …
> workspaceMonitor: Don't toggle overview before startup

- ui/overview.js
- ui/workspaceMonitor.js
From the main commit's message:
```
WorkspaceMonitor reacts to actors being added to, and
removed from, the window group. However - and this is
something me and Andre discussed years ago - this
approach can backfire when windows are added and removed
in quick succession.
So far we didn't have to deal with this case, but
recently, after fixing other bugs elsewhere in the
extension, Hack started to hit it.
Throttling updates is not a perfect solution by any
means, but it's certainly more robust than reacting
to every single actor addition and removal unconditionally.
```
https://phabricator.endlessm.com/T33294
> Start session on app grid

- ui/dash.js
This allows clicking through the empty areas surrounding the Dash,
and potentially interact with apps beneath it, and still show the
Dash.
Change the hover check to observe Main.overview.dash._dashContainer,
which is what actually contains the icons. That limits hovering to
the inner area within Dash that contains icons, but not the entire
Dash covering the screen width.
https://phabricator.endlessm.com/T33219
> Dash click passthrough

- po/POTFILES.in
- settings.js
- ui/panel.js
- utils.js
These three strings are all present and translated into many languages in GNOME Shell itself. By accessing them from the 'gnome-shell' gettext domain, we can reuse those translations. By using this wrapper function that does not match the patterns passed to xgettext by meson, these strings will not be extracted for translation, saving on unnecessary work.
With this change, the only strings remaining in this module are for the internet search provider. (And actually, that code is no longer used, but that's the subject of another ticket!)
This is a bit of a hack but I think it's not an awful approach?
https://phabricator.endlessm.com/T33603
> Reuse translations from GNOME Shell where possible

- ui/overviewControls.js
The signature of this (internal, underscore-prefixed) method changed in
43.beta https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/8562606ad1
and 42.4 https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/dc93377968.
workAreaBox was removed from the argument list, and replaced by a cached
this._workAreaBox.
https://phabricator.endlessm.com/T33774
> overviewControls: Adjust _computeWorkspacesBoxForState signature

- ui/layout.js
Objects should only be created in the enable phase of the extension life cycle.
https://phabricator.endlessm.com/T33660
> layout: Do not create object in global scope

- ui/overviewControls.js
This is what GNOME Shell does in the overriden method. This should have been added since the beginning, and so far it worked out of luck, but after 7d6577321d422f the happy sequence of events we used to hit is no more.
https://phabricator.endlessm.com/T33972
> overviewControls: Hide thumbnails when search is active

- stylesheet.scss
- ui/overviewControls.js
- ui/workspace.js
Sadly `box-shadow` is not viable, so we will try returning to darkening the background in the overview state only, and using this plus a border around the workspace rounded-rectangle to give a crude simulacrum of depth.
I also tried making the top panel always opaque. I think it looks better this way.
New wallpaper from https://github.com/endlessm/eos-media/pull/54:
A light wallpaper I used a few weeks ago:
https://phabricator.endlessm.com/T33971
> Further workspace tweaks

- stylesheet.scss
- ui/overviewControls.js
- ui/workspace.js
Prior to this commit, the font was at regular weight, with a 1px vertical offset, 3px radius and 60% opacity black shadow.
Embolden the font & make the shadow opaque black, with a 2px vertical offset and 2px radius. This matches the settings we had on EOS 4 and makes the app grid legible against the wallpaper now that we have stopped darkening it.
https://phabricator.endlessm.com/T34129
> Embolden font and sharpen shadow on app grid labels

- po/POTFILES.in
`ui/layout.js` was removed in a8190c6d4febbd817d12b79b152dacdb7a888038.
https://phabricator.endlessm.com/T33861
> po: Update POTFILES

- stylesheet.scss
In Shell, $dash_bottom_margin is 16px. Joana's feeling is that,
particularly in our design, this is too wide. 8px is deemed to feel
right.
These are the three rules in _dash.scss from gnome-shell, plus the
variables that they need. (I'm overriding only 'margin-bottom', rather
than the full 'margin' rule.)
https://phabricator.endlessm.com/T33379
> Move the dash closer to the bottom of the screen

- ui/panel.js
When the extension is `enable()`d, two objects are added to
`indicators`.  When `disable()`d, `.destroy()` is called on each element
of `indicators`. But the objects are never removed from `indicators`. So
each subsequent time the extension is enabled and disabled, `.destroy()`
is called on two more already-disposed objects:
Object .Gjs_ui_panel_WorkspacesButton (0x560a39af9db0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x560a35b0d200 ==
#0   560a4c3a3c20 i   /usr/share/gnome-shell/extensions/eos-desktop@endlessm.com/ui/panel.js:196 (28fc36e111a0 @ 87)
#1   560a4c3a3b90 i …
> panel: Clear indicators array after disposing each element

- settings.js
This effectively reverts 85252df74fec2b455afd54a5abb21c894447b814
"migration: Append app center icon to migrated icons" and
f60de8b8def292cb82937076e1c9cd0110aa3302 "settings: Append the app
center icon at the first page".
Since Endless OS 5, which includes GNOME 41, an app cannot be on both
the dash and in the app grid, and the dash takes precedence. The App
Center is on the dash by default. As a result, this code reserves space
on the first page of the app grid for App Center, but it doesn't
actually appear there.
I consulted with Joana on whether App Center should live in the grid or
the dock:
> The dock should hold the main apps, the App Center should be treated
> like that I think.
Remove this special-case. It does mean it is impossible to implement
"Place the App Center at the end …
> settings: Remove Software/App Center special-case

- README.md
- metadata.json.in
- ui/appDisplay.js
- ui/internetSearch.js
A small set of changes to get `eos-desktop-extension` working reasonably well with GNOME 43.
https://phabricator.endlessm.com/T35078
> Support GNOME 43

- ui/dash.js
- ui/overview.js
- ui/panel.js
With this change, clicking the Activities button while the Activities overview is active will consistently exit that mode in one of two fashions. If any windows are open, it will show those windows. If not, the shell will switch to the Applications grid.
In addition, the "Show Apps" button in the dash now behaves consistently with the "Applications" button in the panel. Clicking it when the Applications grid is visible will show either the current open windows, or the overview.
https://phabricator.endlessm.com/T35108
> panel: Clean up transitions between UI modes

- ui/overviewControls.js
A previous commit added a new version of _computeWorkspacesBoxForState for GNOME Shell >= 42, but it was incorrectly computing in a way that made space for a search box. This change computes height in the same way as we did with previous versions of GNOME Shell.
https://phabricator.endlessm.com/T35108
> overviewControls: Use our own size calculations for Shell 42+

- stylesheet.scss
This reverts commit f6604eb6b24edf2b527ba7c80a396c4d09b65458.
These changes were causing a crash on lock / unlock, and some unnoticed alignment issues.
https://phabricator.endlessm.com/T35108
> Revert "style: Modify dash style to match GNOME 41"

- ui/search.js
In 2b1f80d6d184994e35798357a7153902f974cba0, we added code to force the overview to hide when a search result is activated. However, this was incorrectly overriding a (nonexistent) `hide()` function in `Search.SearchResult`. As a result, we have bene using the default behaviour the `activate()` function. It calls `Main.overview.toggle()`, which hides the overview as long as at least one window is visible, giving the illusion that it was working as expected.
Instead, override `activate()` and force the overview to hide even if there are no windows visible at the moment. In addition, provide the same treatment for the signal handler which runs when a search provider is clicked.
https://phabricator.endlessm.com/T35132
> search: Fix the overview staying open on activate

- ui/search.js
81131dc29db09e246d36ec9f4b8515e5f9860d46 (“search: Fix the overview
staying open on activate”) added an override of a method of
Search.ListSearchResults in `enable()` but did not remove it in
`disable()`.
In particular, the extension is disabled whenever the screen is locked,
and reënabled when it is unlocked, leading to infinite recursion in the
overridden ListSearchResults._init() method when it attempts to chain up
to the original implementation.
https://phabricator.endlessm.com/T35132
> search: Restore ListSearchResults when disabled

- ui/dash.js
- ui/overviewControls.js
During Shell's startup animation, an invisible “cover pane” actor is
placed over the entire screen:
// During the initial transition, add a simple actor to block all events,
// so they don't get delivered to X11 windows that have been transformed.
It is removed by the callback passed to
OverviewControls.ControlsManager.runStartupAnimation(), or in our case
the overridden version of it.
Previously, that callback was called from the onComplete() callback for
the ease() transition that slides the dock onto the screen. However it
is possible for a transition to be interrupted before it is complete. In
that case the onStopped() callback passed to ease() will be called (with
argument `false`) but onComplete() will not be.
In this extension, WorkspaceMonitor will trigger a switch out of the …
> Fix Shell input when startup animation interrupted

- ui/appDisplay.js
- ui/dash.js
- ui/overview.js
- ui/overviewControls.js
- ui/search.js
- ui/workspace.js
- utils.js
Mutually depends on:
- https://github.com/endlessm/gnome-shell/pull/760
We override Overview.hide() in such a way that in some cases it actually
ends up showing the overview. Specifically, if there are no visible
windows, the overridden implementation causes the show-apps button to be
pressed; and a ::notify::checked handler for that button in our
extension causes the overview to be shown in some cases.
This was implemented in commit https://github.com/endlessm/eos-desktop-extension/commit/248196ec6917b4152859f5aae619e2fccf8a4cd5
for reasons explained there.
One case where Overview.hide() is called is in response to
MetaMonitorManager::monitors-changed, from Overview._relayout(). This
can happen very early in the session, even before the startup animation
has run. This would cause the …
> Don't try to show app grid during startup animation

- ui/appDisplay.js
- ui/overviewControls.js
Whenever the screen is locked and unlocked, all extensions are, respectively, disabled and enabled. So even though we do not expect users to toggle this extension in regular use, and so do not strictly need the session to be functional when it is manually disabled, we do need turning it off and on again to not cause issues.
Unfortunately, when I disable and re-enable the extension the `gnome-shell` process's resident set size (non-swapped physical memory) grows by (on my system) 30 MiB each time. This also causes the desktop session to become steadily less usable over time. (When testing this, put a `sleep 5` in between each command to disable or enable the extension; if you turn it off and on in a tight loop, gnome-shell crashes, which is bad but I haven't investigated further)
The …
> Fix large memory leak whenever the extension is disabled and enabled
