endlessm/eos-desktop-extension

extension.js, ui/layout.js, ui/overview.js
There are a few pending bits to complete the task, but those two commits bring it closer to the old Endless OS behavior.
https://phabricator.endlessm.com/T30543
=> More Overview Improvements

.gitignore, ui/appDisplay.js, ui/workspaceMonitor.js
Small selection of cleanups and improvements
=> Random Fixes

ui/layout.js, ui/overview.js, utils.js
Add a click action to the overview clone that shows the overview when triggered; and add the background menu when right-clicking the overview.
https://phabricator.endlessm.com/T30543
=> Click Behavior & Background Menu

ui/layout.js
=> Polish, round 2

stylesheet.scss, ui/search.js, ui/workspaceMonitor.js, utils.js
A handful of improvements to search.
https://phabricator.endlessm.com/T30669
=> Search Improvements

ui/internetSearch.js, ui/search.js
Most of the code is just plain copy-pasted from 3.8, but
it required some shenanigans with parental controls to
work properly.
https://phabricator.endlessm.com/T30542
=> Internet Search Provider

debian/control, dirs.js.in, extension.js, meson.build, migration/org.gnome.shell.gschema.xml, schemas/com.endlessm.desktop-extension.gschema.xml, settings.js, ui/iconGridLayout.js, utils.js
https://phabricator.endlessm.com/T30541
=> Settings migration

ui/appDisplay.js, ui/workspaceMonitor.js
See commits. This should ensure we never should all these eos-link- desktop icons.
=> Atomic Bomb Redisplay

settings.js
So it still preserves the position of the app center
icon that Endless OS <= 3.8 had.
https://phabricator.endlessm.com/T30734
=> migration: Add clubhouse icon to migrated icons

extension.js, stylesheet.scss, ui/appDisplay.js, ui/keybindings.js, ui/viewSelector.js
An unassorted bag of improvements of different degrees of relevance. See commit messages
https://phabricator.endlessm.com/T30716
https://phabricator.endlessm.com/T30717
=> Polish, round 4

ui/layout.js, ui/viewSelector.js
Add a click action to the workspaces page and switch back to the app grid when clicking on it.
https://phabricator.endlessm.com/T30023
=> Click action on workspaces page

ui/keybindings.js, ui/layout.js, ui/search.js
As per commit titles.
https://phabricator.endlessm.com/T30788
=> Polish, round 6 (aka burn, ClutterClone, burn)

ui/appDisplay.js, ui/layout.js
A couple of small cleanups I did while investigating the crash when dragging icons.
=> Polish, round 7

settings.js
Not thoroughly tested, but seems to work fine.
https://phabricator.endlessm.com/T30971
=> App Center in the first page

ui/appDisplay.js
(Warning: untested)
We do not need to filter links anymore.
https://phabricator.endlessm.com/T31011
https://phabricator.endlessm.com/T31014
=> Remove _loadApps override

extension.js, settings.js, ui/appSystem.js, ui/iconGridLayout.js
If the method is not already there, redirect to lookup_app;
otherwise, lookup for alias as well.
https://phabricator.endlessm.com/T31115
=> Lookup using alias

settings.js
That commit was completely, absolutely, unequivocably wrong!
https://phabricator.endlessm.com/T31122
=> settings: Fix 49cfb92d6b

ui/internetSearch.js
We are going to direct users to Chromium's Flatpak from flathub.
https://phabricator.endlessm.com/T30997
=> internetSearch: Use Chromium flatpak

stylesheet.scss
As per design direction, add a semi-transparent background
color, with rounded corners.
https://phabricator.endlessm.com/T31028
=> style: Add background to indicators

data/icons/swipe-arrow-symbolic.svg, meson.build, stylesheet.scss, ui/appDisplay.js, ui/layout.js
As per design direction, add navigation arrows. The arrows are actually using swipe arrows to signify that the grid can also be swipped.
https://phabricator.endlessm.com/T32384
---
=> Navigation arrows

extension.js, settings.js, ui/overview.js, ui/overviewControls.js, ui/workspaceMonitor.js
See commits.
First commit fixes https://phabricator.endlessm.com/T32990
The other two commits fix documented issues without a Phabricator ticket.
=> EOS5 polish, round 1

ui/overview.js, ui/overviewControls.js, ui/workspace.js
We need to add them to all monitors, like our ancerstors used
to do in times immemorial.
https://phabricator.endlessm.com/T33019
=> overview: Add wallpapers to all monitors

ui/layout.js
This seems a bit more stable than the current approach, even though it uses ClutterClone.
=> Yet another rewrite of the app grid clone

ui/panel.js
Trivially swap the order in which they're added.
https://phabricator.endlessm.com/T33464
=> panel: Swap Applications and Activities buttons

extension.js, ui/dash.js
This fixes the 3-finger gesture not being able to leave Overview.
https://phabricator.endlessm.com/T33307
=> dash: Leave Overview if there are windows

ui/dash.js
So that it's easier to test new values. The intended usage is
through the Looking Glass, by typing:
Main.overview.dash.setBarrierParams(..., ...)
https://phabricator.endlessm.com/T33221
=> dash: Make barrier configurable

extension.js, ui/dash.js
See commits.
https://phabricator.endlessm.com/T33506
=> Fix Dash again

ui/layout.js, ui/overviewControls.js
Now this for sure works on GNOME 42, but I need to test with Endless OS before landing.
https://phabricator.endlessm.com/T33428
=> More GNOME 42 fixes

ui/layout.js
https://phabricator.endlessm.com/T33660
=> layout: nullify cloneController on disable

stylesheet.scss, ui/overview.js, ui/overviewControls.js, ui/workspace.js
https://phabricator.endlessm.com/T33348
https://phabricator.endlessm.com/T33114
=> General visual polish

stylesheet.scss
As per design suggestion.
https://phabricator.endlessm.com/T33971
=> style: Add text-shadow to top bar

stylesheet.scss, ui/overviewControls.js
Place them both at the same location.
https://phabricator.endlessm.com/T34188
=> overviewControls: Merge search bar and thumbnails

ui/dash.js
This at least gives people a chance to move cursors across
monitors vertically stacked.
https://phabricator.endlessm.com/T33644
=> Support vertically-stacked monitors with primary on top

stylesheet.scss
https://phabricator.endlessm.com/T35108
=> style: Remove overview-specific button styles

debian/control, debian/copyright, extension.js, ui/appDisplay.js, ui/dash.js
Spotted while searching for remnants of eos-watermark-extension.
https://phabricator.endlessm.com/T35077
=> Update source URLs and copyright owners
